/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.netease.backend.collector.rss.common.net;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TUrlInfoResult implements org.apache.thrift.TBase<TUrlInfoResult, TUrlInfoResult._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TUrlInfoResult");

  private static final org.apache.thrift.protocol.TField EXIT_DIFF_VIA_URL_INFOS_FIELD_DESC = new org.apache.thrift.protocol.TField("exitDiffViaUrlInfos", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField PENDING_URLINFOS_FIELD_DESC = new org.apache.thrift.protocol.TField("pendingURLInfos", org.apache.thrift.protocol.TType.LIST, (short)2);

  public List<TURLInfo> exitDiffViaUrlInfos; // required
  public List<TURLInfo> pendingURLInfos; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EXIT_DIFF_VIA_URL_INFOS((short)1, "exitDiffViaUrlInfos"),
    PENDING_URLINFOS((short)2, "pendingURLInfos");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EXIT_DIFF_VIA_URL_INFOS
          return EXIT_DIFF_VIA_URL_INFOS;
        case 2: // PENDING_URLINFOS
          return PENDING_URLINFOS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EXIT_DIFF_VIA_URL_INFOS, new org.apache.thrift.meta_data.FieldMetaData("exitDiffViaUrlInfos", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TURLInfo.class))));
    tmpMap.put(_Fields.PENDING_URLINFOS, new org.apache.thrift.meta_data.FieldMetaData("pendingURLInfos", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TURLInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TUrlInfoResult.class, metaDataMap);
  }

  public TUrlInfoResult() {
  }

  public TUrlInfoResult(
    List<TURLInfo> exitDiffViaUrlInfos,
    List<TURLInfo> pendingURLInfos)
  {
    this();
    this.exitDiffViaUrlInfos = exitDiffViaUrlInfos;
    this.pendingURLInfos = pendingURLInfos;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TUrlInfoResult(TUrlInfoResult other) {
    if (other.isSetExitDiffViaUrlInfos()) {
      List<TURLInfo> __this__exitDiffViaUrlInfos = new ArrayList<TURLInfo>();
      for (TURLInfo other_element : other.exitDiffViaUrlInfos) {
        __this__exitDiffViaUrlInfos.add(new TURLInfo(other_element));
      }
      this.exitDiffViaUrlInfos = __this__exitDiffViaUrlInfos;
    }
    if (other.isSetPendingURLInfos()) {
      List<TURLInfo> __this__pendingURLInfos = new ArrayList<TURLInfo>();
      for (TURLInfo other_element : other.pendingURLInfos) {
        __this__pendingURLInfos.add(new TURLInfo(other_element));
      }
      this.pendingURLInfos = __this__pendingURLInfos;
    }
  }

  public TUrlInfoResult deepCopy() {
    return new TUrlInfoResult(this);
  }

  @Override
  public void clear() {
    this.exitDiffViaUrlInfos = null;
    this.pendingURLInfos = null;
  }

  public int getExitDiffViaUrlInfosSize() {
    return (this.exitDiffViaUrlInfos == null) ? 0 : this.exitDiffViaUrlInfos.size();
  }

  public java.util.Iterator<TURLInfo> getExitDiffViaUrlInfosIterator() {
    return (this.exitDiffViaUrlInfos == null) ? null : this.exitDiffViaUrlInfos.iterator();
  }

  public void addToExitDiffViaUrlInfos(TURLInfo elem) {
    if (this.exitDiffViaUrlInfos == null) {
      this.exitDiffViaUrlInfos = new ArrayList<TURLInfo>();
    }
    this.exitDiffViaUrlInfos.add(elem);
  }

  public List<TURLInfo> getExitDiffViaUrlInfos() {
    return this.exitDiffViaUrlInfos;
  }

  public TUrlInfoResult setExitDiffViaUrlInfos(List<TURLInfo> exitDiffViaUrlInfos) {
    this.exitDiffViaUrlInfos = exitDiffViaUrlInfos;
    return this;
  }

  public void unsetExitDiffViaUrlInfos() {
    this.exitDiffViaUrlInfos = null;
  }

  /** Returns true if field exitDiffViaUrlInfos is set (has been assigned a value) and false otherwise */
  public boolean isSetExitDiffViaUrlInfos() {
    return this.exitDiffViaUrlInfos != null;
  }

  public void setExitDiffViaUrlInfosIsSet(boolean value) {
    if (!value) {
      this.exitDiffViaUrlInfos = null;
    }
  }

  public int getPendingURLInfosSize() {
    return (this.pendingURLInfos == null) ? 0 : this.pendingURLInfos.size();
  }

  public java.util.Iterator<TURLInfo> getPendingURLInfosIterator() {
    return (this.pendingURLInfos == null) ? null : this.pendingURLInfos.iterator();
  }

  public void addToPendingURLInfos(TURLInfo elem) {
    if (this.pendingURLInfos == null) {
      this.pendingURLInfos = new ArrayList<TURLInfo>();
    }
    this.pendingURLInfos.add(elem);
  }

  public List<TURLInfo> getPendingURLInfos() {
    return this.pendingURLInfos;
  }

  public TUrlInfoResult setPendingURLInfos(List<TURLInfo> pendingURLInfos) {
    this.pendingURLInfos = pendingURLInfos;
    return this;
  }

  public void unsetPendingURLInfos() {
    this.pendingURLInfos = null;
  }

  /** Returns true if field pendingURLInfos is set (has been assigned a value) and false otherwise */
  public boolean isSetPendingURLInfos() {
    return this.pendingURLInfos != null;
  }

  public void setPendingURLInfosIsSet(boolean value) {
    if (!value) {
      this.pendingURLInfos = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EXIT_DIFF_VIA_URL_INFOS:
      if (value == null) {
        unsetExitDiffViaUrlInfos();
      } else {
        setExitDiffViaUrlInfos((List<TURLInfo>)value);
      }
      break;

    case PENDING_URLINFOS:
      if (value == null) {
        unsetPendingURLInfos();
      } else {
        setPendingURLInfos((List<TURLInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EXIT_DIFF_VIA_URL_INFOS:
      return getExitDiffViaUrlInfos();

    case PENDING_URLINFOS:
      return getPendingURLInfos();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EXIT_DIFF_VIA_URL_INFOS:
      return isSetExitDiffViaUrlInfos();
    case PENDING_URLINFOS:
      return isSetPendingURLInfos();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TUrlInfoResult)
      return this.equals((TUrlInfoResult)that);
    return false;
  }

  public boolean equals(TUrlInfoResult that) {
    if (that == null)
      return false;

    boolean this_present_exitDiffViaUrlInfos = true && this.isSetExitDiffViaUrlInfos();
    boolean that_present_exitDiffViaUrlInfos = true && that.isSetExitDiffViaUrlInfos();
    if (this_present_exitDiffViaUrlInfos || that_present_exitDiffViaUrlInfos) {
      if (!(this_present_exitDiffViaUrlInfos && that_present_exitDiffViaUrlInfos))
        return false;
      if (!this.exitDiffViaUrlInfos.equals(that.exitDiffViaUrlInfos))
        return false;
    }

    boolean this_present_pendingURLInfos = true && this.isSetPendingURLInfos();
    boolean that_present_pendingURLInfos = true && that.isSetPendingURLInfos();
    if (this_present_pendingURLInfos || that_present_pendingURLInfos) {
      if (!(this_present_pendingURLInfos && that_present_pendingURLInfos))
        return false;
      if (!this.pendingURLInfos.equals(that.pendingURLInfos))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TUrlInfoResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TUrlInfoResult typedOther = (TUrlInfoResult)other;

    lastComparison = Boolean.valueOf(isSetExitDiffViaUrlInfos()).compareTo(typedOther.isSetExitDiffViaUrlInfos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExitDiffViaUrlInfos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.exitDiffViaUrlInfos, typedOther.exitDiffViaUrlInfos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPendingURLInfos()).compareTo(typedOther.isSetPendingURLInfos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPendingURLInfos()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pendingURLInfos, typedOther.pendingURLInfos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // EXIT_DIFF_VIA_URL_INFOS
          if (field.type == org.apache.thrift.protocol.TType.LIST) {
            {
              org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
              this.exitDiffViaUrlInfos = new ArrayList<TURLInfo>(_list0.size);
              for (int _i1 = 0; _i1 < _list0.size; ++_i1)
              {
                TURLInfo _elem2; // required
                _elem2 = new TURLInfo();
                _elem2.read(iprot);
                this.exitDiffViaUrlInfos.add(_elem2);
              }
              iprot.readListEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // PENDING_URLINFOS
          if (field.type == org.apache.thrift.protocol.TType.LIST) {
            {
              org.apache.thrift.protocol.TList _list3 = iprot.readListBegin();
              this.pendingURLInfos = new ArrayList<TURLInfo>(_list3.size);
              for (int _i4 = 0; _i4 < _list3.size; ++_i4)
              {
                TURLInfo _elem5; // required
                _elem5 = new TURLInfo();
                _elem5.read(iprot);
                this.pendingURLInfos.add(_elem5);
              }
              iprot.readListEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.exitDiffViaUrlInfos != null) {
      oprot.writeFieldBegin(EXIT_DIFF_VIA_URL_INFOS_FIELD_DESC);
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, this.exitDiffViaUrlInfos.size()));
        for (TURLInfo _iter6 : this.exitDiffViaUrlInfos)
        {
          _iter6.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    if (this.pendingURLInfos != null) {
      oprot.writeFieldBegin(PENDING_URLINFOS_FIELD_DESC);
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, this.pendingURLInfos.size()));
        for (TURLInfo _iter7 : this.pendingURLInfos)
        {
          _iter7.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TUrlInfoResult(");
    boolean first = true;

    sb.append("exitDiffViaUrlInfos:");
    if (this.exitDiffViaUrlInfos == null) {
      sb.append("null");
    } else {
      sb.append(this.exitDiffViaUrlInfos);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pendingURLInfos:");
    if (this.pendingURLInfos == null) {
      sb.append("null");
    } else {
      sb.append(this.pendingURLInfos);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

